### ISSUE TITLE
[Task] Ignore upper lower case for command keyword

### ISSUE THREAD

**Issue by wenxin-c** [AY2223S2-CS2113-T12-4/tp#100]
**Task**
What is the task this feature aims to achieve?  
Ignore upper lower case for input command keyword

**Is your feature request related to a problem? Please describe.**
This is to allow users to input either capital or small letters to achieve at same functionality

**Describe the solution you'd like**
Ignore upper lower case in comparision or convert command keyword to small letters

**Comment by nichyjt** [comment]
This can be done on the `CommandParser` level. I can make the changes for these.

To clarify, this means that commands such as:
```
UPDATE --id 5
updatE --id 5
uPdAtE --id 5
update --ID 5
```

Will all be accepted and converted to:
```
update --id 5
```
