### ISSUE TITLE
[Enhancement] Adding print dot method

### ISSUE THREAD

**Issue by wenxin-c** [AY2223S2-CS2113-T12-4/tp#109]
**What is the current behaviour? Please describe any relevant features.**
Printing dot ```.``` is very often used in many features/methods, for each object the prints ```.```, it needs to create a constant attribute of ```.```.  

**Why should this behaviour be changed/improved? Describe any relevant user stories/frustrations.**
Since the same function is used multiple times, it will be good if it can be extracted out. 

**Describe your proposed enhancement.**
We can add a public ```printDot()``` public method to TestUi class. Since most of the classes that require printing output will have TestUi object being created, they can just call this method to print ```.``` instead of creating new constant.  

**Why should this enhancement be added? Explain its benefits/significance.**
It will be easier to print ```.``` and the codebase will become neater.

**Comment by nichyjt** [comment]
Closed by #106
