### ISSUE TITLE
[Task] Rename `logger` as LOGGER

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#111]
**Describe the Task**
Loggers are inaccurately named.
They are declared as constants, but do not follow the constant naming structure.

This is found in `commandParser` and many instances under the `reflection` package

**Expected behavior**
Logger should be renamed as `LOGGER`

**Screenshots**

**Comment by wenxin-c** [comment]
```commandParser``` class line 42 ```logger``` is used instead of ```LOGGER```
![image](https://user-images.githubusercontent.com/89572803/228521433-5accdf21-8a67-4ac8-aa55-86a2b2ccad1e.png)
