### ISSUE TITLE
[Bug] Atomic habits logo bad format

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#112]
## Describe the bug
Atomic habits logo seems to be output buggily with off by one errors

## To Reproduce
Enter these in order in the terminal
```
hb
```

## Screenshots
![image](https://user-images.githubusercontent.com/69704055/225806955-c0ab2a08-27ab-48d2-b699-8693e04d5e20.png)

## Desktop (please complete the following information):
 - OS: Linux (Ubuntu 22.04, Pop_OS!)
 - Intellij Bash terminal

## Affected Codeowners
@YongbinWang @BernardLesley 
Could you verify this behaviour on your end?

**Comment by wenxin-c** [comment]
This is addressed.
