### ISSUE TITLE
[Bug] Atomic Habit `list` uncaught bad user input

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#113]
## Describe the bug
Atomic habit `list` can accept a payload and arguments without error. 

## To Reproduce
Steps to reproduce the behavior on terminal:
```
hb
add --name some long habit
list # This is OK as expected
list foo # This is OK, but shouldn't be 
list --bar # This is OK, but shouldn't be
list foo --bar # This is OK, but shouldn't be
list foo --bar baz # This is OK, but shouldn't be
```

## Expected behavior
Error messages to be shown for these adversarial command inputs:
```
list foo
list --bar
list foo --bar
list foo --bar baz
```

## Screenshots
![image](https://user-images.githubusercontent.com/69704055/225807901-ba835a37-827b-4efa-8694-97c8615ac666.png)

## Affected Codeowners
@BernardLesley @YongbinWang 
Is this behaviour supposed to happen?

I think people will flag this out as not handling errors properly, so we should change it.

**Comment by nichyjt** [comment]
For reference, this is marked as low severity as it does cause any breaking behaviour.

**Comment by wenxin-c** [comment]
These bugs have been fixed, the followings are the current behaviour which are expected. 
![image](https://user-images.githubusercontent.com/89572803/228524973-ff516ac2-8352-4af0-a144-c2564c4e2a92.png)
![image](https://user-images.githubusercontent.com/89572803/228525017-52583ffe-44df-47b9-9458-5a0169f12dfa.png)
