### ISSUE TITLE
[Bug] Atomic Habit `update` increment accepts 0 increment

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#114]
## Describe the bug
Atomic habit allows users to `update` with `--inc 0`

## To Reproduce
```
hb
add --name some long habit
update --id 1 --inc 0
```

## Expected behavior
Users and testers might expect an error message to be shown. Maybe something quirky like "You didn't update anything!"

## Screenshots
![image](https://user-images.githubusercontent.com/69704055/225808798-58c3b763-2640-4465-ab41-2db413fc0a1a.png)

**Additional context**

## Affected Codeowners
@YongbinWang @BernardLesley 
Is this expected behaviour? Do we want to catch this type of input?

**Comment by haoyangw** [comment]
This has been fixed in #125. Closing.
