### ISSUE TITLE
[Bug] Atomic Habit extra payload not caught on `home`

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#117]
## Describe the bug
When `home` is appended with a payload, such as `home getPwned`, it executes the command without an error message.
Meanwhile

This is inconsistent behaviour that may be flagged out during evaluation.  

This also hints at a possible uncaught `validateCommand` edgecase. 

## To Reproduce
```
reflect
home getPwned
```
## Expected behavior
Error message to be printed out on `home getPwned`

## Screenshots
![image](https://user-images.githubusercontent.com/69704055/225815267-f3fe2e1e-574b-447c-aad7-17889be268e6.png)

![image](https://user-images.githubusercontent.com/69704055/225815386-84e93d57-90cc-4108-8855-6ec71f093fe9.png)

## Affected Codeowners
@YongbinWang Is this expected behaviour? Do you think that the extra payload should cause an error to be raised/printed?

**Comment by nichyjt** [comment]
I

> Hmm this was partially fixed in #125, but introduced another bug or perhaps a separate bug now surfaced. Should we close @nichyjt @wenxin-c ? New issue for the 'new' bug is at #139

I think we should close this since its technically solved. We focus on solving the regressive bug at #139

**Comment by haoyangw** [comment]
Alright, sounds good to me. Let's go to #139 from now on
