### ISSUE TITLE
[User Story Feature] Add integrated storage functionality 

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#131]
## User Story
As a user, I want to be able to store data from `Atomic Habits`, `Reflection` and any other future features.

## Is your feature request related to a problem? Please describe.
Currently, all features' state does not persist after WellNUS++ terminates. This means that things that on a conceptual level that the user expects to be saved, such as `Atomic Habit`s are not saved, which is frustrating to the user as their hard earned progress is not saved.

## Describe the the solution you'd like
An extensible way to save data for the user.  

From discussions, the general idea is to have a `Storage` class in charge of the actual IO for saving and loading of data.  
This is accompanied by an `OOP` based Tokenizer approach
- A common Tokenizer interface defined, forcing a common function signature 
- The implementation of Tokenization to the features that require saving/storage

## Breakdown of User Story
This user story will require 3 separate tasks
1. Setup of `Storage` boilerplate
2. Setup of `Tokenizer` boilerplate
3. Implementation of `Tokenizer`

**Comment by wenxin-c** [comment]
```Tokenizer``` for atomic habit and self reflection have finished.
Implementation of storage for self reflection and atomic habit have finished.
