### ISSUE TITLE
[Bug] Insufficient exception handling for invalid home command of atomic habits

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#139]
**Describe the bug**
Giving an invalid `home` command sometimes throws the generic BadCommandException instead of one with the specific invalid home command message that's introduced in #125. 

**To Reproduce**
One method to reproduce the behavior:
1. Issue `hb` command
2. Issue `home --Test`, which throws the specific invalid home command message introduced in #125
3. Issue `home Test`, which now throws the generic BadCommandException message from `MainManager`
4. User was taken back to `MainManager` already, even though `home Test` is not a valid home command

Another method to reproduce the behavior:
1. Issue `hb` command
2. Issue `home Test`, which throws the specific invalid home command message introduced in #125 
3. Issue `home --Test`, which now throws the generic BadCommandException message from `MainManager`
4. User was taken back to `MainManager` already, even though `home Test` is not a valid home command

**Expected behavior**
Step 3 in both test cases above should give user the specific invalid home command message introduced in #125, and user should **not** be taken back to `MainManager`.

**Comment by wenxin-c** [comment]
This bug has been fixed, users will not go back ```MainManager``` if home command is invalid. 
![image](https://user-images.githubusercontent.com/89572803/228526882-68bc2378-c078-479b-b6c3-15d5fa5d4d7d.png)

**Comment by haoyangw** [comment]
Fixed by #203, closing this
