### ISSUE TITLE
[User Story Feature] Get introspective questions

### ISSUE THREAD

**Issue by wenxin-c** [AY2223S2-CS2113-T12-4/tp#17]
**User Story**
As a reflective computing student, I wish to get a set of introspectvie questions on demand so that I can reflect and grow emotionally at my own pace. 

**Is your feature request related to a problem? Please describe.**
Due to hectic and fast paced school work, I always do not have time to reflect on myself. What I have achieved/learned so far in the semester? What skills I wish to obtain in the future? What I have done correctly or what are the areas of improvement? Sometimes I do not know what to start with to reflect on myself. Hence, I wish to have an opportunity to have a set of frequently asked introspective questions and use them to reflect on myself as well. 

**Describe the solution you'd like**
Users can ask WellNUS++ to get a **random** set of introspective questions for users to view.
Command: 
```
get
```
A set of 5 random introspective questions will be generated. For example: 
```
Here’s some questions for you:
1. What’s one thing you are grateful for today?
2. What do I need to change about myself?
3. Am I letting matters that are out of my control stress me out?
.
.
.
N. What is one thing you are proud of today?
```

**Additional context**
At this point, every time users will get a random set of introspective questions. This is for users to get exposed to different questions and possibly reflect on different apsects of themselves. At later stages, users can LIKE a specific question and review it afterwards.

**Comment by nichyjt** [comment]
For the reflection questions, you can consider adapting some from [this research-backed source](https://www.usa.edu/blog/self-discovery-questions/) by a US University!
