### ISSUE TITLE
DG Review

### ISSUE THREAD

**Issue by qianz-z** [AY2223S2-CS2113-T12-4/tp#195]
1. In your group's Reflection Component, it is difficult to see the naming of the Objects. Try using a different font colour for that.
![image](https://user-images.githubusercontent.com/85693125/228730287-43faee5b-9755-44bf-8584-580657652058.png)

2. In your group's Reflection Component, there are many arrows are intersecting one another, and hence making it very difficult to read. Try arranging the arrows around or use a different way to show this. 
![image](https://user-images.githubusercontent.com/85693125/228730439-ebc0b901-f9a6-44f8-8544-e1331ef18464.png)

3. The same goes for your AtomicHabit Component. The arrows are too close to each other at the bottom right and it is difficult to see which multiplicity belongs to which arrow.
![image](https://user-images.githubusercontent.com/85693125/228731100-df7308f2-10ed-4ea4-82ab-9a6be9f22bfe.png)
 
4. For your class diagrams, there are non-standard representations for the method visibility. It shouldn't be using circle, diamond and square format.
![image](https://user-images.githubusercontent.com/85693125/228730550-e42a1fb2-c6f1-43f4-b5cb-b30fc1aac477.png)

5. If possible, for every object deletion, end the lifeline right where the cross is and not extend the lifeline below that.

**Comment by wenxin-c** [comment]
Sequence diagram color changed, visibility notation changed and class diagrams are simplified.
