### ISSUE TITLE
[Boilerplate Feature] Manager event driver abstract class

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#22]
## Boilerplate Feature
`Manger` event driver class as a common interface to build features off for WellNUS++

## Is your feature request related to a problem? Please describe.
Currently the codebase is missing important common interfaces to break-into new features.  

The architecture as planned thus far as a team:
- Each feature will be launched from the main driver `WellNus.java`
- Each feature effectively runs as its own main driver  
- Each feature needs to have its own event driver
- Each feature will handle its own input logic verification, as hinted at in #19 

There will be repeated work when our various features `atomic habits`, `reflection` need to implement the common behaviours listed above.

## Describe the solution you'd like
A `command` class that should minimally covers these behaviours:
1. `runEventDriver` to begin the feature event driver
2. `isValidCommand` that needs to be implemented
3. Hold a list of valid commands, usage and descriptions  (for `help`)
4. `exit` to leave the feature event driver (up to `runEventDriver` implementation)
5. `getFeatureKeyword()`: Returns the command keyword, e.g. hb, timer
6. `getArgumentsForFeatureDescription()`: Returns the full list of arguments supported by the feature, e.g. add [--name] for hb
7. getBriefDescriptionOfFeature(): Returns a brief description of this feature to be printed by the basic help command
8. getFullDescriptionOfFeature(): Returns a full description for the corresponding specialised help command of this feature, e.g. help hb for hb

**Comment by haoyangw** [comment]
Some suggested shared behavior(and their functionality) for `Managers`(to put in the abstract superclass):
-getFeatureKeyword(): Returns the command keyword, e.g. hb, timer
-getArgumentsForFeatureDescription(): Returns the full list of arguments supported by the feature, e.g. add [--name] <name> for hb
-getBriefDescriptionOfFeature(): Returns a brief description of this feature to be printed by the basic help command
-getFullDescriptionOfFeature(): Returns a full description for the corresponding specialised help command of this feature, e.g. help hb for hb
-isValidCommand(): Accepts a HashMap of commandline arguments and returns a boolean for whether they represent valid input for this Command
-goToFeature(): Brings user to the specific feature's user interface, where feature-specific commands are then available. Expectation is goToFeature() will exit and return to its parent event driver when user elects to exit the feature

**Comment by nichyjt** [comment]
Thanks for the feedback! 👍🏼 

I agree with the points. I'll add them to the main issue thread.

The `goToFeature` is functionally the `run` function. Perhaps better naming is required on my end!

**Comment by nichyjt** [comment]
On further thought, @haoyangw do you think it makes sense if:

`isValidCommand()`  throws an exception rather than return a boolean?  (if yes, then I'll rename this to `validateCommand` to follow coding conventions

This way we can pass a custom exception message so that we know exactly what went wrong with the command. This should help with debugging efforts too when we start implementing it.

A good side effect is that it also forces us developers to be aware of the exception and handle it via `catch` properly
