### ISSUE TITLE
[PE-D][Tester A] [Feature Flaw] Unable to remove favorited reflection questions from the list 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T12-4/tp#224]
Although users are able to add the questions that they like to reflect about in future into their favorites list, in the events users mistyped and added a question they did not meant to add, users are unable to delete it from the list. Hence the list can only keep growing until the whole question bank may be filled at one point. Would be good to allow for users to delete reflective questions that they no longer resonate with or want to look at anymore.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Aung-Phone-Naing/ped#2

**Comment by wenxin-c** [comment]
This is addressed.
