### ISSUE TITLE
[PE-D][Tester E] Whitespace error on hb `help` command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T12-4/tp#226]
![image.png](https://raw.githubusercontent.com/stevenantya/ped/main/files/13caac6b-21be-4f2c-a7eb-f20f307512f0.png)

whitespace created an error

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: stevenantya/ped#5

**Comment by wenxin-c** [comment]
This is addressed.
