### ISSUE TITLE
[PE-D][Tester E] Incomplete Documentation (gamif)

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T12-4/tp#228]
![image.png](https://raw.githubusercontent.com/stevenantya/ped/main/files/e162664c-79b0-4cf2-8df1-2b8467a28c3d.png)

The instruction in the UserGuide produces error!

![image.png](https://raw.githubusercontent.com/stevenantya/ped/main/files/c5d0930d-056f-4ae4-9349-7bd33da074e7.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: stevenantya/ped#6

**Comment by wenxin-c** [comment]
`gamif` command is not available in Atomic Habit feature.
