### ISSUE TITLE
[Bug] Payload in MainManager not properly handled

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#255]
**Describe the bug**
Adding a payload in the main page with a feature name does not get handled.

**To Reproduce**
```
<anyMainFeature> foobar
```
**Expected behavior**
The command should not go through.

**Screenshots**
![image](https://user-images.githubusercontent.com/69704055/229499032-27090830-c36c-4668-9d3b-2608478502a4.png)

**Comment by wenxin-c** [comment]
This bug happens for `exit` command as well.
![image](https://user-images.githubusercontent.com/89572803/229730877-b0464156-19b6-4e2d-8ff9-62f4b4932cc1.png)
