### ISSUE TITLE
[Bug] Input cursor not printed correctly

### ISSUE THREAD

**Issue by YongbinWang** [AY2223S2-CS2113-T12-4/tp#270]
**Describe the bug**
The input cursor for main is not printed correctly due to logger printing to command line output.

**To Reproduce**
1. corrupt the data file for either habit or reflect
2. run wellnus.main()
**Expected behavior**
Logger should not be printed, if it is to be printed, cursor should be after the logger file. Can consider adding a next line after logger.

**Screenshots**
![image](https://user-images.githubusercontent.com/74821808/230139283-5bd7bbc3-2e8a-433f-af38-6b15bc876b08.png)

**Comment by nichyjt** [comment]
This seems to have been addressed in #272

**Comment by haoyangw** [comment]
Indeed. No longer an issue. Closing
