### ISSUE TITLE
[Bug] UserGuide topmost `help` command section unclear

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#297]
**Describe the bug**
<img width="298" alt="image" src="https://user-images.githubusercontent.com/9844161/230711274-bd7b2b46-75a3-461d-a9f4-3f69fa4d71ac.png">
Not immediately clear which kind of `help` invocation leads to which based on the wording. Can be clearer. Needs to look at the example usage to understand what the description is saying, which is unideal.

**Expected behavior**
What is written in the individual feature sections for the feature-specific `help` is clearer, e.g. in atomic habits:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/9844161/230711368-81f82797-ba7d-4fca-bcce-47de9caa0f3b.png">

**Comment by wenxin-c** [comment]
Fixed by #348
