### ISSUE TITLE
[Bug] Atomic Habit able to add empty habit empty habit 

### ISSUE THREAD

**Issue by BernardLesley** [AY2223S2-CS2113-T12-4/tp#298]
**Describe the bug**
Currently Atomic Habit is able to add an empty habit, which is not inteded.

**To Reproduce**
1. type hb
2. type add --name

**Expected behavior**
An error message should be thrown

**Screenshots**
<img width="341" alt="image" src="https://user-images.githubusercontent.com/67412977/230711403-c6d007dc-e4d4-49fa-81a6-073403c081d8.png">

**Desktop (please complete the following information):**
- Windows

**Comment by wenxin-c** [comment]
Fixed by #337
