### ISSUE TITLE
[Bug] Empty log files being created

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#299]
**Describe the bug**
On clean launch of wellnus++ and exit, then re-launch, quite a few log files are being created.

The files are empty. Is this expected behaviour? @haoyangw 

![image](https://user-images.githubusercontent.com/69704055/230711474-67410cd0-b1e7-42ca-bc3d-eb86c9a4e882.png)

**Comment by haoyangw** [comment]
Ok did some research, there is a bug in the current `WellnusLogger` implementation. Will address in a future PR, assigning this to myself.
