### ISSUE TITLE
[Bug] User guide example output indentations are wrong

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#301]
**Describe the bug**
Indentations for user guide outputs seem to be wrong in various places. 

UG Example:
![image](https://user-images.githubusercontent.com/69704055/230711754-3742ff66-c68f-45fe-b2b2-01d0267c5237.png)

Actual Output:
![image](https://user-images.githubusercontent.com/69704055/230711769-f50c6982-6f37-4bf3-9c95-b07f8d25d419.png)

**Comment by wenxin-c** [comment]
Fixed by #339
