### ISSUE TITLE
[Bug] Quick Start section unclear

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#302]
**Describe the bug**
<img width="373" alt="image" src="https://user-images.githubusercontent.com/9844161/230711469-c5cabcdf-02c0-4e3f-a516-8284764e53d1.png">
Quick Start section ends after telling the user to run the jar file. But if this is a new user, what command should they start with? And it none of the first 5 sections explain that we have **two** kinds of 'sessions', the 'main' and the 'feature' session, and that the user starts in the main session.

**Expected behavior**
A 5th step in the `Quick Start` section providing some suggestions on what the user can do first. e.g. below the screenshot of the `WellNUS++` greeting in the `Quick Start` section, add:
 `5. You are now in the 'main' session. Type 'help' to see a list of supported features and their commands, namely 'hb', 'reflect', 'gamif'. By issuing a feature command, you will be taken to the feature session. Type 'help' to see a list of supported feature commands. Return to the main session using 'home' command.`

**Comment by wenxin-c** [comment]
Fixed by #348
