### ISSUE TITLE
[Enhancement] Unclear `update` error when hb list is empty

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#305]
**What is the current behaviour? Please describe any relevant features.**
When `update` command is issued without first adding an atomic habit, the error message given is not helpful and doesn't help a new user figure out what to do next:
<img width="425" alt="image" src="https://user-images.githubusercontent.com/9844161/230711933-cef3ba89-e987-4f25-a0bc-bd47409347e9.png">

**Why should this behaviour be changed/improved? Describe any relevant user stories/frustrations.**
The error message doesn't guide the user about what to do next to make the `update` command work.

**Describe your proposed enhancement.**
More descriptive error message that informs the user to first `add` an atomic habit and also check out `help add` to figure out how to use the `add` command.

**Why should this enhancement be added? Explain its benefits/significance.**
User will know what to do next even without looking at the user guide or memorising all our commands or typing `help` on their own. This is a good user experience improvement to make our app more beginner-friendly.

**Comment by wenxin-c** [comment]
Fixed by #337
