### ISSUE TITLE
[Bug] `hb`, useless `update` by 0 gets accepted 

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#306]
**Describe the bug**
`update --id some_id --by 0` is allowed.
Functionally, it does nothing. This is useless behaviour that could be caught and handled. As a tester and user, I **might** expect that to happen.

This may likely be flagged out as a `FEATURE_FLAW`. 

![image](https://user-images.githubusercontent.com/69704055/230712104-8ae5e992-ddf4-4c0f-88a4-a5cd0b4cd58a.png)

If this is to be fixed, UG needs to be updated as well.

**Comment by wenxin-c** [comment]
Fixed by #337
