### ISSUE TITLE
[Bug] `hb` on adding new habit, it might make more sense to start from 0

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#308]
**Describe the bug**
Potential feature flaw.

When `add` ing a new habit, it instantiates the number of times I did this habit to be 1.

This might not make logical sense to testers and users. We are assuming that added habits have already been done once.

But consider the case that I want to 'exercise' as a habit. I have not exercised yet, but plan to do it as a habit.
Logically, the habit set should be 0. 

It also makes sense if I have a habit im already tracking outside of `hb`. Say I know that I have exercised `N` times.
I can simply --update by `N` rather than `N-1`. (This is why lots of things start from 0 too!)

If fixed, UG should be updated to reflect that it will be initiated as 0.

**Comment by wenxin-c** [comment]
Fixed by #347
