### ISSUE TITLE
[Bug] `hb` when `update` with negative values, output message is wrong

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#312]
**Describe the bug**
Possible feature flaw.

When i decrement a habit, the message appears:
![image](https://user-images.githubusercontent.com/69704055/230712572-b4472fdd-f07b-4ecc-842a-e336d5db5e9d.png)

This does not make sense. The habit is NOT incremented, and it shouldn't be congratulating me. This is weird from a user POV.

**Comment by wenxin-c** [comment]
Fixed by #337
