### ISSUE TITLE
[Enhancement] Unclear gamification User Guide

### ISSUE THREAD

**Issue by BernardLesley** [AY2223S2-CS2113-T12-4/tp#317]
**What is the current behaviour? Please describe any relevant features.**
Currently, the user guide does not really explain how user can increase their level

**Why should this behaviour be changed/improved? Describe any relevant user stories/frustrations.**
The user might get confused on how the leveling system works, for example they might wonder why the XP does not go up when they add new habit, get reflect, or start timer.

**Describe your proposed enhancement.**
Maybe can consider adding explanation regarding how the gamif calculates XP, and which activities can increase XP.

For example: Updating your habit can increase your XP by .... 

**Screenshots(if any) of the enhancement.**
<img width="563" alt="image" src="https://user-images.githubusercontent.com/67412977/230712924-a7d18d52-43ab-49f3-8a8f-ca59639dfc6c.png">

**Why should this enhancement be added? Explain its benefits/significance.**
It would be clear to the user how the gamif system works and therefore motivates the user to work on their habit.

**Comment by wenxin-c** [comment]
Fixed by #348
