### ISSUE TITLE
[Bug] corrupted file inconsistent behaviour

### ISSUE THREAD

**Issue by wenxin-c** [AY2223S2-CS2113-T12-4/tp#318]
**Describe the bug**
The rest features silently swallow the error but gamif print it out

**To Reproduce**
1. Corrupt file with `ab`

**Screenshots**
![image](https://user-images.githubusercontent.com/89572803/230713125-565c01e1-6af9-4616-af5d-94f3a76a71ef.png)

**Comment by haoyangw** [comment]
Wait i think we should make all the features print out the error though, a corrupted data file is a minor issue but still an issue, and we're overriding the data, so we should ideally tell the user we're doing that. What do the rest think?

**Comment by haoyangw** [comment]
Similar issue #321, will close that one. Resolve both bugs under this issue please.

**Comment by wenxin-c** [comment]
Fixed by #349
