### ISSUE TITLE
[Bug] Corrupted habit file throwing error at the start of the program

### ISSUE THREAD

**Issue by BernardLesley** [AY2223S2-CS2113-T12-4/tp#321]
**Describe the bug**
Currently if the hb file is corrupted and user start wellnus, confusing error might show up

**To Reproduce**
1. corrupt hb file
2. start wellnus++

**Expected behavior**
The error message should be hidden, the tester might flagged out this behavior because reflect does not throw such error

**Screenshots**
<img width="335" alt="image" src="https://user-images.githubusercontent.com/67412977/230713326-02fc2f31-11ef-4818-a40d-6ffd0501bfcf.png">

<img width="530" alt="image" src="https://user-images.githubusercontent.com/67412977/230713238-7b3505cc-15f4-46b4-9135-3e926f094e17.png">

**Comment by haoyangw** [comment]
Wait I think `reflect` should be the one with a bug, we _do_ want the user to realise that the data file is corrupted and data will be lost! But perhaps we need to find a way to move the error message lower, after the greeting, somehow

**Comment by haoyangw** [comment]
Too similar to #318. Closing this. Please update in #318 any progress/clarifications
