### ISSUE TITLE
[Bug] Remove unused command syntax in User Guide

### ISSUE THREAD

**Issue by nichyjt** [AY2223S2-CS2113-T12-4/tp#326]
**Describe the bug**

The user guide specifies that:  

![image](https://user-images.githubusercontent.com/69704055/230714293-889027a7-d42f-4e6b-a580-ab163905d92e.png)

This is not used anywhere in WellNUS++. Let's remove this to prevent confusion on the user's side.

**Comment by haoyangw** [comment]
I believe this is fixed? @nichyjt am i right

**Comment by nichyjt** [comment]
Yes, fixed!

**Comment by haoyangw** [comment]
Alright, closing
