### ISSUE TITLE
[Bug] Inaccurate error message for update command

### ISSUE THREAD

**Issue by YongbinWang** [AY2223S2-CS2113-T12-4/tp#329]
**Describe the bug**
The output error message for update command when an integer too large is inputted.

**To Reproduce**
1. update --id 1 --by 12323123213123213
**Expected behavior**
Error message should be saying integer too large 
**Screenshots**
![image](https://user-images.githubusercontent.com/74821808/230714471-264743b1-2b4a-45af-b4ac-4b7d35595595.png)

**Comment by haoyangw** [comment]
Already specified in #303. Closing this
