### ISSUE TITLE
[Enhancement] Remove habit if it is decremented to 0

### ISSUE THREAD

**Issue by YongbinWang** [AY2223S2-CS2113-T12-4/tp#330]
**What is the current behaviour? Please describe any relevant features.**
Currently habit stays in list when it has been decremented to 0.

**Why should this behaviour be changed/improved? Describe any relevant user stories/frustrations.**
Users would prefer it to be deleted if it is 0.

**Describe your proposed enhancement.**
Remove it from list if it is 0.

**Screenshots(if any) of the enhancement.**
![image](https://user-images.githubusercontent.com/74821808/230714522-be4570ed-7e69-4189-911d-cd4dd0db9e31.png)

**Comment by haoyangw** [comment]
We will default to habit count 0 when first added, so this now becomes intended behaviour(don't remove habits with count `0`)
