### ISSUE TITLE
[Bug] Error output message not accurate in habit(delete)

### ISSUE THREAD

**Issue by YongbinWang** [AY2223S2-CS2113-T12-4/tp#331]
**Describe the bug**
When inputting a lot of space before the habit index in delete, error message is not very accurate.

**To Reproduce**
1. See screenshot below.
**Expected behavior**
Updated error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/74821808/230714564-0b137fd2-545e-45fc-8588-9b9c665fb4d8.png)

**Comment by haoyangw** [comment]
Already specified in #310, closing.
