### ISSUE TITLE
[Bug] Documentation output bug

### ISSUE THREAD

**Issue by YongbinWang** [AY2223S2-CS2113-T12-4/tp#332]
**Describe the bug**
Printing of start session output is not accurate.

**To Reproduce**
1. Go to view userguide portion on start command.

**Expected behavior**
Output should be more accurate.

**Screenshots**
![image](https://user-images.githubusercontent.com/74821808/230714657-95322c08-40c7-492e-a8a1-15dbc498e8c7.png)

**Comment by wenxin-c** [comment]
This is fixed.
