### ISSUE TITLE
[Bug] BadCommandException not thrown for empty string

### ISSUE THREAD

**Issue by wenxin-c** [AY2223S2-CS2113-T12-4/tp#40]
**Describe the bug**
When pass an empty string into ```parser.setCommandType()```, a ```BadCommandException``` is expected but it is not thrown in JUnit test. 

**To Reproduce**
1. Create a JUnit test for this method
2. Use lamda function and pass an empty string into this method
3. Use assertThrows to catch exception
4. Exception is not thrown

**Expected behavior**
A BadCommandException is thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/89572803/224348466-bf587457-c886-4dc5-b0a6-8813607b970a.png)

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - 10

**Comment by nichyjt** [comment]
Good catch, will fix this asap.
