### ISSUE TITLE
[Task] Checking next line in UI read input

### ISSUE THREAD

**Issue by wenxin-c** [AY2223S2-CS2113-T12-4/tp#42]
**Purpose**
The ```readNextline()``` is called in UI class read input method, adding a check before reading to ensure there is always a new line when ```readNextline()``` is called. 

**Is your feature request related to a problem? Please describe.**
Reading a new line that does not exist will lead to ```NoSuchElementException```. 

**Describe the solution you'd like**
Adding a check ```hasNextline()``` before reading for checking purpose to ensure there is always a new line when reading next line.

**Comment by nichyjt** [comment]
Maybe it's better to rename the title to [Task] rather than feature since this is not really a feature

**Comment by wenxin-c** [comment]
The noSuchElementException is already catched by ```getCommand()``` method and handled by printing error messages, so this issue can be closed.
