### ISSUE TITLE
[Task] Change request: move validateCommand from Manager class to Command class

### ISSUE THREAD

**Issue by wenxin-c** [AY2223S2-CS2113-T12-4/tp#53]
**Task**
What is the user story this feature aims to achieve?  
Instead of validating command in Manager class, having it in Command class will be better. 

**Is your feature request related to a problem? Please describe.**
It is difficult to validate all possible kinds of commands and relavant arguments-payloads pairs in Manager class.

**Describe the solution you'd like**
Move abstract method ```validateCommand()``` from ```Manager``` class to ```Command``` class. Have this method to be abstract to force all subclasses override to check validation of commands.

**Comment by nichyjt** [comment]
@haoyangw what are your views on this?

When I discussed with wx offline she shared her difficulties in understanding how to implement validate command on the Manager level. Of course, I can think of a way to make this possible but...

Should validation be done on Manager or Command level?

I thought about it and I now think it may be better to do it on command level.  
If we implement on Manager the method might be quite long as we are aggregating all the command validation logic in one place. This won't scale very well. 

Command level validation will nicely decouple the components
