### ISSUE TITLE
[Enhancement] Auto wrapping for UI output

### ISSUE THREAD

**Issue by wenxin-c** [AY2223S2-CS2113-T12-4/tp#55]
**Feature**
What is the user story this feature aims to achieve?  
To standardise output length, set auto wrapping of output if it exceeds a specific length. 

**Is your feature request related to a problem? Please describe.**
If the output is too long, it might not fit into the length of separators. 

**Describe the solution you'd like**
To be searched on..

**Comment by nichyjt** [comment]
This issue was depreciated due to low priority for v2.1.
