### ISSUE TITLE
[Task] Basic Logging

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#56]
**Describe the Task**
Introduce some basic logging of important events such as unintended(but recoverable) situations and runtime exceptions.

**Expected behavior**
Log should include details of all important events that occurred during the runtime of WellNus, such as the cause of runtime exceptions.

**Additional context**
Important events we want to keep track of in the log for now:
-Unusual but recoverable situations, e.g. Invalid command/argument issued by the user
-Runtime exceptions, e.g. I/O exception while reading user input
Details we want to include in the log:
-Causes of the situation/exception
-Which class and method the situation/exception occurred in
-Type of event, e.g. I/O-related, Command-related

**Comment by wenxin-c** [comment]
Logging has been added.
