### ISSUE TITLE
[Enhancement] Helpful Invalid Command Message

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#58]
**What is the current behaviour? Please describe any relevant features.**
User is given the same message whenever any invalid command is issued, notifying him/her the command is not recognised.

**Why should this behaviour be changed/improved? Describe any relevant user stories/frustrations.**
In the case that the user issued an invalid command when he/she is unaware of the proper usage of a given command, he/she needs to learn the proper usage of the command. This would require calling another command, `help`, which is a minor inconvenience.

**Describe your proposed enhancement.**
Print a brief description of the given command's syntax instead of a generic invalid command message.

**Screenshots(if any) of the enhancement.**
```

> help 3

Unrecognised argument '3' given for the command 'help'. Usage:
help <feature>

```

**Why should this enhancement be added? Explain its benefits/significance.**
This eliminates the need to call another command, `help` in order to find out how to properly use a given command, which improves the user experience and efficiency of WellNus.

**Comment by nichyjt** [comment]
This seems to be an extension of the `help` feature and was wrongly labelled as v1.0, hence the shift.
