### ISSUE TITLE
[Enhancement] Refactor atomic habits feature

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#60]
**What is the current behaviour? Please describe any relevant features.**
Atomic habit code defines its own classes to manage commands.

**Why should this behaviour be changed/improved? Describe any relevant user stories/frustrations.**
`Command` and `Manager` classes have been merged. They ensure a common feature set amongst all features so conceptually, atomic habit should extend its command logic from those base classes.

**Describe your proposed enhancement.**
Refactor atomic habit code to extend from `Command` and `Manager`.

**Why should this enhancement be added? Explain its benefits/significance.**
Refactoring atomic habits' command logic to extend from those base classes makes the code base easier to maintain and also more streamlined. This is better for the team long-term.

**Comment by nichyjt** [comment]
Closed by #72
