### ISSUE TITLE
[Enhancement] SelfReflection implementation

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#85]
**What is the current behaviour? Please describe any relevant features.**
SelfReflection defines all of its state as `static`, which means every instance of `SelfReflection` shares the same state and can modify one another's state. 

State is also initialiased in the constructor, and `getQuestions()` appears to expect the constructor to be called beforehand(calling `SelfReflection.getQuestions()` directly leads to undefined behaviour), but there is no need to do so since `SelfReflection.getQuestions()` is a valid function call from any `Class`, anywhere.

**Why should this behaviour be changed/improved? Describe any relevant user stories/frustrations.**
Seems to be dangerous and prone to bugs. Mainly because the compiler allows such undefined behaviour as calling `SelfReflection.getQuestions()` without initialising `SelfReflection` via `new SelfReflection()`, but this is guaranteed to lead to a crash, so such code shouldn't be allowed to compile, if possible.

In fact, it's already responsible for the crash in `GetCommand.execute()` of the self reflection feature(see `Additional context` below), so ideally we should close this loophole to reduce potential bug hunting in the future.

**Additional context for related issues**
Example of crash in `GetCommand.execute()`:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/9844161/225553872-b1646f4d-9097-44c5-ba88-0853741dd9f6.png">
The danger with these kinds of crashes is from the `Exception` message, it isn't immediately obvious what is causing the crash. Directly Googling the Exception message doesn't lead to relevant advice/situations either. In my opinion it would be a waste of development time if such issues surface in the future and debugging drags on because of the undescriptive `Exception`.
Additionally, relevant parts of `SelfReflection` are flagged out in the IDE(`IntelliJ`) as unintended usage of Java:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/9844161/225554829-619d9878-899b-4518-a6f8-2c0093030e24.png">
From my understanding, this is because Java expects `static` methods to never depend on any instantiation made in the constructor(I recommend reading the `Initialization Order for Classes with Inheritance` section on [order of initialistion in Java](https://infinitescript.com/2014/09/object-initialization-order-in-java/)). This is an important idea to keep in mind since it leads to undefined behaviour.

**Describe your proposed enhancement.**
Minimise use of `static` attributes/methods, apart from `static final` constants, unless code cannot work without them. 

**Any alternative implementations/enhancements that were considered?**
Writing assertions in `static` code that have expectations about state with a descriptive assertion error message to help with debugging these kinds of undefined behaviour.
I would avoid this because you need to be completely aware that you are breaking Java's order of initialisation to be able to put the assertions in the right place, and assertions are not enabled by default in Java. Too dangerous in my opinion

**Why should this enhancement be added? Explain its benefits/significance.**
2 reasons to avoid `static` attributes/methods in my opinion:

1. It's easier to change your implementation to avoid `static` than to figure out the source of weird bugs arising from order of initialisation in Java. Because fixing such bugs require understanding the order of initialisation(a confusing concept), which we can avoid by sticking to `instance` attributes/methods as far as possible.
2. Code with significant `static` attribute/method usage won't integrate well with code that don't. Because you cannot call `instance` attributes/methods from `static` methods, unless you use workarounds that break Java convention.

**Comment by nichyjt** [comment]
Thanks @haoyangw for the detailed writeup and post-mortem analysis of the crash. This is an excellent learning point for the whole team. 
 
Haoyang, I agree with the proposed changes for SelfReflection. The benefits make sense and I've actually mentioned these in my PR reviews before. For reference:
- https://github.com/AY2223S2-CS2113-T12-4/tp/pull/35#discussion_r1133057443 <- buggy behaviour
- https://github.com/AY2223S2-CS2113-T12-4/tp/pull/27#discussion_r1131179789 <- extensibility

To prevent this from happening again, as rule of thumb:
`static final` and `static` should be reserved **only** for constants. Refer to https://github.com/AY2223S2-CS2113-T12-4/tp/pull/31#discussion_r1131876665

By constants, I mean magic literals that have only one state (its literal value).

From now on, I propose that this should be much more strictly checked during PRs.

To add on to the discussion, I think the whole intent behind the agreed upon architecture through the `Command` and `Manager` boilerplate is to **instantiate** all variables that have **state** within the constructor. This is enforced through the `abstract` methods. This should have made integration much less difficult and more standardized. 

Let's be more careful with the way we use the `static` keyword from here onwards.

What do the others think?

**Comment by wenxin-c** [comment]
```SelfReflection``` class has been refactored into a different class and unnecessary static attributes have been removed.
