### ISSUE TITLE
[Enhancement] Setup checkstyle to enforce CS2113 Coding Style

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#89]
**Describe your proposed enhancement.**
Import the checkstyle config for CS2113 coding style from the [addressbook-level3 repo](https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle). Setup your IntelliJ to enforce the coding style using [this guide](https://se-

**Why should this enhancement be added? Explain its benefits/significance.**
Coding style is one of the graded components for this project, and it's much more efficient to fix coding style violations downstream than have to flag them manually during PR review.

**Comment by nichyjt** [comment]
This is closed by #128.

Thank you @haoyangw , @BernardLesley , @YongbinWang , @wenxin-c for the quick work and collaboration as a team with all the PRs (#125 #126 #127) 🎉
