### ISSUE TITLE
[User Story Feature] Help Command

### ISSUE THREAD

**Issue by haoyangw** [AY2223S2-CS2113-T12-4/tp#97]
**User Story**
New users would need a familiar command to access a detailed explanation of what WellNUS++ provides and how to use its features/commands.

**Describe the solution you'd like**
The basic `help` command without any arguments should print an overall description of all the supported features in WellNUS++ and the arguments supported by each feature.

**Comment by nichyjt** [comment]
Rectification: After a quickl meeting, feature specific `help` command has been decided to be dropped in favor of a more straightforward solution
